name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
      - uses: actions/checkout@v1
      - name: Install Elm
      - uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Checkout gh-pages
      - run: git checkout gh-pages
      - name: Build Elm code
      - run: elm make src/Main.elm --optimize --output=main.js
      - name: Push to gh-pages
      - run: git add index.html main.js && git commit -m "Action build" && git push
