name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19.1
    - uses: action/checkout
      with:
        ref: gh-pages
    - run: elm make src/Main.elm --optimize --output=main.js
    - run: git add index.html main.js && git commit -m "Action build" && git push
